language: python
sudo: false
python:
 - 3.5 # otherwise we can't run tox 3.5 tests
env:
  matrix:
    - TOXENV=py35
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=flake8
addons:
  apt:
    packages:
      # Some tests do a pdf conversion, so install latex which is needed for that.
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - lmodern
install:
  - travis_retry pip install tox
  # only download pandoc, the tests should work without a install of pypandoc
  - python setup.py download_pandoc

script:
  - ./pypandoc/files/pandoc -v
  - tox

after_success:
  # remove pandoc again as we don't want it in the uploaded sdist
  - rm -r ./pypandoc/files

deploy:
  provider: pypi
  distributions: sdist
  user: janschulz
  password:
    secure: uxmjO7Q0MP0YZb1pdAkKn7TdLdFU1lJqrnSR5DpjzPpJRlGMUph0MIrtHtU1CsbMya//Wwszae77pEqAIDpQ5mHlfF3mPxSO8TWvYu6XZdkmmTKf3rIaJgYoOIz1VdyHsti5SIHMBE749eUykTwNrqV4OR+lk3fpdZmy8shl7+U=
  on:
    tags: true
    repo: bebraw/pypandoc
    condition: $TOXENV == py35
