language: python
sudo: required
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=flake8
services:
  - docker
addons:
  apt_packages:
    - pandoc
install:
  - travis_retry pip install tox
script:
  - tox
