language: python
sudo: required
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=flake8
services:
  - docker
addons:
  apt_packages:
    - pandoc
    - pandoc-citeproc
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - lmodern
install:
  - travis_retry pip install tox
script:
  - pandoc --version
  - tox
