environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  TWINE_PASSWORD:
    secure: vwvitc1udvvzJrSNBbxQrtNKPACCOpSM3kteJK6UBR8=
  TWINE_USERNAME: janschulz

  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # stolen from https://github.com/doxygen/doxygen/blob/master/appveyor.yml
  - appveyor-retry appveyor DownloadFile  https://miktex.org/download/win/miktexsetup-x64.zip
  - 7z e miktexsetup-x64.zip
  - appveyor-retry miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential download
  - miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential --shared install
  - refreshenv
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - initexmf --admin --set-config-value "[MPM]AutoInstall=1"


  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "%CMD_IN_ENV% python -m pip install --disable-pip-version-check --user --upgrade pip"

  - "%CMD_IN_ENV% python -m pip install twine wheel"

build_script:
  - "%CMD_IN_ENV% python setup.py download_pandoc"
  - "%CMD_IN_ENV% pypandoc\\files\\pandoc --version"

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% python -m pip install tox"
  - "%CMD_IN_ENV% tox"

after_test:
  # If tests are successful, create binary packages for the project.
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

on_success:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        # we produce version independent packages, so once per "big" version is enough
        if ($env:PYTHON_VERSION -eq "3.7.x" -or $env:PYTHON_VERSION -eq "2.7.x") {
          twine upload dist/*.whl
        }
      }
