name: PyPandoc CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash
 
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        os: [macos-10.15, windows-2019, windows-2016, ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python setup.py develop
    - name: Download Pandoc
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install pandoc
        elif [ "$RUNNER_OS" == "Windows" ]; then
          python setup.py download_pandoc
        else
          sudo brew install pandoc
        fi
    - name: Test with pytest
      run: |
        python tests.py
